apiVersion: v1
kind: Service
metadata:
  name: "redis"
  namespace: "default"
  labels:
    app: "redis"
spec:
  selector:
    app: redis
  ports:
    - name: http
      port: 6379
      targetPort: 6379
  type: LoadBalancer