apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "flask-pubsub-hpa"
  namespace: "default"
  labels:
    app: "flask-pubsub"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "flask-pubsub"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 70