apiVersion: v1
kind: Service
metadata:
  name: "flask-pubsub-service"
  namespace: "default"
  labels:
    app: "flask-pubsub"
spec:
  selector:
    app: flask-pubsub
  ports:
    - name: http
      port: 80
      targetPort: 5002
  type: LoadBalancer