apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "flask-celery-config"
  namespace: "default"
  labels:
    app: "flask-celery"
data:
  DATABASE_URL: "postgresql://postgres:postgres@34.23.114.143:5432/converter"
  REDIS_URL: "redis://104.196.15.16:6379/0"
