apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "flask-celery"
  namespace: "default"
  labels:
    app: "flask-celery"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "flask-celery"
  template:
    metadata:
      labels:
        app: "flask-celery"
    spec:
      containers:
      - name: "converter-web-sha256-1"
        image: "gcr.io/miso-mobile-2023/converter-web@sha256:9f6fbae5d8bde0ecb1bce6b80d8b1c3a91fbcd4768fbeefba52717f6815e3b25"
        command: [ "celery", "-A", "api.tasks.tasks", "worker", "--loglevel=INFO" ]
        env:
        - name: "DATABASE_URL"
          valueFrom:
            configMapKeyRef:
              key: "DATABASE_URL"
              name: "flask-celery-config"
        - name: "REDIS_URL"
          valueFrom:
            configMapKeyRef:
              key: "REDIS_URL"
              name: "flask-celery-config"
        - name: "GOOGLE_APPLICATION_CREDENTIALS"
          valueFrom:
            configMapKeyRef:
              key: "GOOGLE_APPLICATION_CREDENTIALS"
              name: "flask-celery-config"
