apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "flask-web-hpa-2j45"
  namespace: "default"
  labels:
    app: "flask-web"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "flask-web"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 70